### ISSUE TITLE
Otter.gen Nowhere to be found

### ISSUE THREAD

**Issue by alexedstrom** [barryrowlingson/geostat#1]
Barry,

I appreciate your contribution to the Geostat 2014 course and I was looking to brush up on my basic command-line/awk scripts. I was looking for the "otter.gen" file you used in your unix scripting section and cannot find it. Can you please load?

Thanks you.

**Comment by barryrowlingson** [comment]
Alex,

 I've added all the fake otter data to the github pages here:

https://github.com/barryrowlingson/geostat/tree/gh-pages/data/otters

 if there's anything else I've missed, let me know!

Barry

**Comment by alexedstrom** [comment]
Thanks Barry.

On Wed, Feb 25, 2015 at 2:55 AM, Barry Rowlingson notifications@github.com
wrote:

> Alex,
> 
> I've added all the fake otter data to the github pages here:
> 
> https://github.com/barryrowlingson/geostat/tree/gh-pages/data/otters
> 
> if there's anything else I've missed, let me know!
> 
> Barry
> 
> On Tue, Feb 24, 2015 at 1:09 AM, Alex notifications@github.com wrote:
> 
> > Barry,
> > 
> > I appreciate your contribution to the Geostat 2014 course and I was
> > looking to brush up on my basic command-line/awk scripts. I was looking
> > for
> > the "otter.gen" file you used in your unix scripting section and cannot
> > find it. Can you please load?
> > 
> > Thanks you.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/barryrowlingson/geostat/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/barryrowlingson/geostat/issues/1#issuecomment-75933536
> .

## 

_Alex EdstromUniversity of Idaho, M.S. Water Resources - 2011_
_University of Idaho, B.S. Bio. and Ag. Engineering - 2009_
